// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockApplication.API.Context;

#nullable disable

namespace StockApplication.API.Migrations
{
    [DbContext(typeof(StockApplicationContext))]
    partial class StockApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("StockApplication.API.Entities.HardwareSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allimentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpu")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphicCard")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Storage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("HardwareSpecs");
                });

            modelBuilder.Entity("StockApplication.API.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("StockApplication.API.Entities.NetworkSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpGateway")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpMask")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("VlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("NetworkSpecs");
                });

            modelBuilder.Entity("StockApplication.API.Entities.HardwareSpecs", b =>
                {
                    b.HasOne("StockApplication.API.Entities.Item", "Item")
                        .WithOne("Specs")
                        .HasForeignKey("StockApplication.API.Entities.HardwareSpecs", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StockApplication.API.Entities.NetworkSpecs", b =>
                {
                    b.HasOne("StockApplication.API.Entities.Item", "Item")
                        .WithOne("Network")
                        .HasForeignKey("StockApplication.API.Entities.NetworkSpecs", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StockApplication.API.Entities.Item", b =>
                {
                    b.Navigation("Network");

                    b.Navigation("Specs");
                });
#pragma warning restore 612, 618
        }
    }
}
